language:
- objective-c
env:
  global:
      #- BUILD_COMMIT=latest-tag
    - BUILD_COMMIT=pr/6442
    - REPO_DIR=matplotlib
    - NIPY_WHEEL_URL=https://nipy.bic.berkeley.edu/scipy_installers
    - FT_VERSION=2.5.3
    - PNG_VERSION=1.6.12
    - ZLIB_VERSION=1.2.8
    - TCL_URL=http://downloads.activestate.com/ActiveTcl/releases
    # Need to check these last two from time to time
    - TCL_VERSION=8.5.18.0
    - TCL_DMG=ActiveTcl8.5.18.0.298892-macosx10.5-i386-x86_64-threaded.dmg
  matrix:
    - VERSION=2.7.10 NUMPY_VERSION=1.7.1
    - VERSION=3.4.3 NUMPY_VERSION=1.7.1
    - VERSION=3.5.0 NUMPY_VERSION=1.7.1
install:
# increase number of open files allowed for tests
# https://github.com/matplotlib/matplotlib/issues/3315
- ulimit -n 4096
- source run_install.sh
- get_python_environment macpython $VERSION venv
- pip install delocate
# Allow nipy wheelhouse for Python 3.5 wheel
- pip install -f $NIPY_WHEELHOUSE numpy==$NUMPY_VERSION
# Update to latest wheel package for Python 3.5
- pip install -U wheel
# Get branch to test
- (cd $REPO_DIR && git fetch origin pull/6442/head:${BUILD_COMMIT})
- if [ -n "$BUILD_COMMIT" ]; then
      checkout_commit $REPO_DIR $BUILD_COMMIT;
  fi
- source mpl_install.sh
- mpl_build_install
script:
# Fix numpy ast errors in tests by upgrading numpy
- if [ -n "$(pyver_ge $VERSION 3.4.0)" ]; then
  pip install --upgrade numpy;
  fi
- pip install nose mock sphinx
- install_activestate_tcl
- MPLBACKEND="tkagg" python -c 'import matplotlib.pyplot as plt; print(plt.get_backend())'
- mpl_test
before_deploy:
  - cd $REPO_DIR/dist
deploy:
  provider: cloudfiles
  username: travis-worker
  api_key:
    secure: K9JEFezfB40JDYntdoBKfxFD6qAlWGo1WaNM269JUAS6+8taD8gLOe83r1hyZWa0m2hdTilk0ySDUxjs+aTe2f4+ES+s8aiORSTFHChMUL/7+vteaHUle3BEuUDx23mnx5XNQT/n1gX2WkWwqZMH7JDAsHbexuquQZfJVAWRpo4=
  region: ORD
  container: wheels
  skip_cleanup: true
