language:
- objective-c
env:
  # global: LATEST_TAG=1
  matrix:
  - VERSION=2.7.8 NUMPY_VERSION=1.5.1
  - VERSION=3.3.5 NUMPY_VERSION=1.7.1
  - VERSION=3.4.1 NUMPY_VERSION=1.7.1
install:
- source run_install.sh
- get_python_environment macpython $VERSION venv
- pip install -f $NIPY_WHEELHOUSE numpy==$NUMPY_VERSION
- pip install delocate
- if [ -n "$LATEST_TAG" ]; then checkout_closest_tag matplotlib; fi
- source mpl_install.sh
- mpl_build_install
script:
- mpl_test
before_deploy: cd matplotlib/dist
deploy:
  provider: cloudfiles
  username: travis-worker
  api_key:
    secure: PTlIH2hjQKw+pme9nCEs/KpjjmEHT5/G/jkjgglx22nWYnSr+zzs9yA803qEFnC/5qwoZN5dC/mgXZHLgFgmBCqpM5JP+FrAMTTVeDNfk6lWLq5QMdjZPtoJDjjVBqA0NJFSfWmrXzXVaNkNORBoKnL3JNI0C4gNpyVQRr2eqgQ=
  region: ORD
  container: wheels
  skip_cleanup: true
