language:
- objective-c
env:
  # global: LATEST_TAG=1
  matrix:
  - VERSION=2.7.8 NUMPY_VERSION=1.5.1
  - VERSION=3.3.5 NUMPY_VERSION=1.7.1
  - VERSION=3.4.1 NUMPY_VERSION=1.7.1
install:
- source run_install.sh
- get_python_environment macpython $VERSION venv
- pip install -f $NIPY_WHEELHOUSE numpy==$NUMPY_VERSION
- pip install delocate
- if [ -n "$LATEST_TAG" ]; then checkout_closest_tag matplotlib; fi
- source mpl_install.sh
- mpl_build_install
script:
- mpl_test
before_deploy: cd matplotlib/dist
deploy:
  provider: cloudfiles
  username: travis-worker
  api_key:
    secure: K9JEFezfB40JDYntdoBKfxFD6qAlWGo1WaNM269JUAS6+8taD8gLOe83r1hyZWa0m2hdTilk0ySDUxjs+aTe2f4+ES+s8aiORSTFHChMUL/7+vteaHUle3BEuUDx23mnx5XNQT/n1gX2WkWwqZMH7JDAsHbexuquQZfJVAWRpo4=
  region: ORD
  container: wheels
  skip_cleanup: true
